Repository Group-5-Project-2/CodeCave, pull requests merged in 2020-08, with the labels that each got.

#35 32 friend list components
  client/package-lock.json
  client/public/index.html
  client/public/manifest.json
  client/src/App.js
  client/src/components/FriendList/Friend.jsx
  client/src/components/FriendList/ListGroup.jsx
  client/src/components/FriendList/ListHeader.jsx
  client/src/components/FriendList/RemoveButton.jsx
  client/src/components/FriendList/SearchFriends.jsx
  client/src/components/FriendList/friendTest.json
  client/src/components/FriendList/index.jsx
  client/src/components/FriendList/style.css
  client/src/components/Homepage/Button.js
  client/src/logo.svg
Labels: MVP

#51 50 readme
  README.md
Labels: documentation

#67 63 link login
  README.md
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/App2.js
  client/src/components/Footer/footer.css
  client/src/components/Footer/index.jsx
  client/src/components/Landing/Cave.jpg
  client/src/components/Landing/index.jsx
  client/src/components/Login/index.jsx
  client/src/components/Login/login.css
  client/src/components/Navbar/index.jsx
  client/src/components/Profile/index.jsx
  client/src/components/Register/index.jsx
  client/src/components/UserFunctions.jsx
  client/src/controls/TextFieldGroup.js
Labels: Back End, Front End, MVP, documentation
